git:
  depth: 5
language: node_js
node_js:
- stable
deploy:
  provider: npm
  email: pedre87@gmail.com
  on:
    branch: master
  api_key:
    secure: PCVynq5hCE6ksekb9PUtYuPIXFfbkY2SUnhnrjGRTLZ4Qot7LN2BR2o+HC46q+HcC5plzuHhqkXypy7FrHNrFqhd3WZ4k7bNAuPXYX6mYlMy6M89TtHlfyuB/WO8kA7si5RkAGiGmwzsPpTYorLD697sY+IFweFc2HqHAcc8vzBF0EsZac3q/7HVo85xX0FYyHTDB6XhD2axoZwYqHMYpypo3Owm1r65acPUkcp0W4cBUWlFgw+rIQtYs5DrlZUCJmPBlfeWkqihUrMsWHQmIcXkWVfbNLPZL/gMCIuzusaiTGhN7c8TRQvH8AuWevoznz1MJI2I55NC0vHyjOd9c5OlWJ1zkmnZ4fVyGyRnmk7pzkL1uYadPPVi0I1xtv9M2fyVqDu6BDjemHC1e2Nis2rAdq/V6uZqlOc2nMXpZQBtExtrl2kZ7rH0uTddfruVgItTFll2tifGNdxegS5VPoe5Hefy7lnjc4XrxQHNk2juvLW77z3mnfDPcFEOZNfKtym7XBXHeM6M+SX5NOD/Ayn/bWwAI01RLfCpExbAQEsMY6uolILSUiZzbyRB16cPLjKDEwDhoyjCtRxKOLdvbyr7MnbeSBsAc2M6lw7lFVmOjOVG2n2/hM7+2vvFKq1t6DEhWg1iLhY+r0DV02urrzbteE5W5P+gcYuzBP3ZWSg=
