git:
  depth: 5
language: node_js
node_js:
- stable
deploy:
  provider: npm
  email: pedre87@gmail.com
  on:
    branch: master
  api_key:
    secure: J5MoJ8g9pTjDCgE0eBxMwxQ9bADbM153pyQJLDtYd7ZVv65wRVLEIPhXVF1d6Q9Ox18wGKNYzzKBAcMel93a5Fm1lKXZaBpb7L2WlwJoyo0XZlllBcMDcwhhRhkUiN+dfehAa05UuTVkcC3lyZrVEFejshChRyVwpKydEgk31dbqFzyatbmgM56yNpnMYIlep0qrJM7qVda0qbvuxTcSLMvF9sbkd1II9MGjhn/eW1U+pkl5PeqC5IM7/RbChTjcWHTOeWlpyXzKQ2YIXX8ie2BuZLnv0S90gTqNhDI8GI9PP3bOTBjGO05HQtD5+bV1Fd4olO5399WnoguQQOSzGEHUWyH8zsYB6bocAbSM23iK0s4AVLUSbEfCKtWfHT3M8IjG42qs5ZAfK14myk4+OyHt0hoOHdomUi5Q5fwLMr/DU1125N8GV9l0oacEICsvzXnE6/xyaakNAnzAzNI0As+C55G+zpPR9jmjz22ux6aRcaIC2Hv21vvcyz3z3tlJtZyJ3wxWbxm9OJoH+2uzWcTzmOS0P3EaW8MZwZyj9hzIGcmDXg+r1kdbmWDwnTaKVWSc5RJH65f+fMKQCHpAcKNTgjkr1xqj4KnnLthR/xquiABZun5DYXhJB5b5aEFijNT0INGjWHRTCRNOgcCrGdvnEmNx8UU64qKqVhxA3Tk=
script:
- nohup yarn test
