git:
  depth: 5
language: node_js
node_js:
- stable
deploy:
  provider: npm
  email: pedre87@gmail.com
  on:
    branch: master
  api_key:
    secure: Carvvcq2h68Zec5/N/Nklp/QygY4x+uZ8c2vBxhWzGgSLTf4e5FrUcZIB8yX+t/0RxLGwDMvtWDZr88CGoxdgZMuqOxFFsTo5X0BAU4wndXmXNivAhxcOmts2mGhukQQ99gTvTLQz+flUdbkjaS2aZD/QbAgfjV/3nc+bZZ8J0EyzbVOrfaXLKYNtMFLLvkDrCKW9BbgtgXnQ0uEPLcgheSWPsfp0ke9T+heyfrjgi2Uu8eKoYnZFOmsEMB14szSuoRdPlp+pMAHeKVFeignATcL/kucSdw7aIonKnRehtIQDCHoKGz5g/aoMpb3GHRHMDsJWRK22pCDsyk8Hc3UY9wYPOfgnGEsI0P/HYCxxUA50J1sbniIIDhZGDeZPwRDFBJTLoR3mE44S25Lhhe9eVvYBp5NM0AUSA7QHg77//cVtM8L/2u7a/51sE923lo/w0jhFfdrT9U9CVgJ+GfYVOQsayHJjfM2pwco3zRomnnFCOEaGqvcF+LKzqBhrTUCVpmMA7n3BbDdXO8wlT4HczTEuaMjD2RlX4/p2ROEARoQlq80JgY6bSBKDKDDWnb7rE/NpxYgt8f7Yzs+liDMCXFxxoyIRVj7+mG8giSrVdzRNPR4Iy0v8n0wsx67ZjgMbRYygKI9K0zWdmh6EzYI9V/uoxKfJQOPZm3OnIgI2/Y=
script:
- nohup yarn test
