git:
  depth: 5
language: node_js
node_js:
- stable
deploy:
  provider: npm
  email: pedre87@gmail.com
  on:
    branch: master
  api_key:
    secure: pNPeYIS71Ilwr0ehBmegfT/UDwJdzpShQbNQSJfs05JP1R+YPY1b/2Bc+Qw1nIMM5Y3DtpuqnMo2ESeiLGvQIcxaqbFwMvXZO+PsFWQSRUAkwl9H0MjYjLi45UQsa9mWLA2KhhgoXQKHvQPY63HQ+nYnfC3nqZnUN09YZDWxMw3LB8lle/ehpF9XsBejtx+EBHWkV5i//nx5FYxdwFh1cTGr2RUxsw1VqaQAAMqQNURNZjR2Vne5eik895on+jumg94oGe+EZ/rhnS2u7n/0ZjYdJl0xiM0AmEpas8xRdbCmxBFExm9FjBf+IAj5XqOB3oz4V5vE1U3NkCwpnScTXtVyhgf/0z1fiW0pzWx3ls63XnS68nInDFg4nH1oJRHiLOMBC8FdKlC/wcRIB1ytiHZJuEDEx771Ab6pxC+RazySw4ZDcNB2mhOhYPVrvlLnfKlJmDEQh8hGkBCVmOsCWg5xJv14zBxk7GGnim0464QAYhOk8KzR4cJ5vbiWShdC98OWHpkK4kBUOmLtlrdZxtXFDh2AmpTfb3S8sWmA9cBt46O7cHtWDxPLxQw/3nsJZvt86k7dpOQ2B77m9LPe9QrGuzgYxX2SJuvRYVbrjAEjy7DdHJfxZ0H6dap/2+Q7gidlW9wfWuxyjiEELnSoi48yKFFp/owMWyaFyfDHmNU=
script:
- nohup yarn test
