language: node_js
node_js:
- stable
deploy:
  provider: npm
  email: pedre87@gmail.com
  on:
    branch: master
  api_key:
    secure: WTx1kKn3U9uOlRnxrX25c2Gc0y0Bu+3cc5Utnn9IYSgc5YIgBZ31sNK3dSoLfZQjY84yeaLLQwPS7md0drW6XfRAsjH/q+/H5iivdeuk3tGAIFsWqAyoIxCpMh7ZHzU4RN0G0VeAQO7f6SVA5lSgy/42XOkcGcDxGuSZlXXoCh7L1rWx7zCvk2whrUlJrWco99ZG9IXsQ3oWvkHKyz8RFMQU1KMXheonNFX8YpDc8+UI2ZJs1/22sV8wkj2UddX+lFvSdFGwK5Qw47ZpelbVYHbRQ4dVkhL3cwxRe8WglK/nTu0T6hcjtiPq25h2hpg8AMra40J3RjuZCHKH5ZZXAvyW/4NWdusAkQGX2e1XOTzUAy2i1faz+uo9K8rN6AUpRye08DytrLp3no+uQbjRLzcaSO2+7VCsLmA7XEpAAan6Z9SpDooLUsrlU91WZZ9ktIba8JJ32PAxkEpjpe+TFd/TqUT/F+Cr7FqBmHZl0JBFbqJz84Gkr1XCBIktdAiLXV4kLhwcAcCFhr/SSjLghGgBzQfx8e0/xJmKQPQrF88rVQ9mA02gptQIS4hvMLom16vgStjxJPn4napoFlYQr0+T4PjZ9cL13Chyf2PsVdk6eJzx5oIEBBPjZk0hMw3UYgF+vafJklH/t+v8Nq+ejvBlVe39FGpm0KVkQLMsScg=
