version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.9.1

jobs:
  setup:
    <<: *defaults
    steps:
      -checkout
      
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .
    
    deploy:
      <<: *defaults
      steps:
        - attach_workspace:
          at: ~/repo
        - run:
          name: Authenticate with NPM registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
        -run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  setup-deploy:
    jobs:
      - setup
        filters:
          branches:
            only:
              - develop
              - master
      - deploy:
          filters:
          branches:
            only:
              - master
